### ISSUE TITLE
Docs 404 on Github Pages other than the index.

### ISSUE THREAD

**Issue by Skyyrunner** [Skyyrunner/JeevesCoursePlanner#18]
How to reproduce:

Go to http://skyyrunner.github.io/JeevesCoursePlanner/
Click any link.
404.

**Comment by simonseo** [comment]
Hello @Skyyrunner 
Try creating a gh-pages branch and then navigate to https://skyyrunner.github.io/JeevesCoursePlanner/docs/

I forked your repository and did the above and [it worked](https://simonseo.github.io/JeevesCoursePlanner/docs/).

**Comment by Skyyrunner** [comment]
Nice, implemented.
